name: "🐞 Bug Report"
description: "Report a bug with a YAGSL mechanism or motor wrapper"
title: "[BUG] <short summary>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue! Please provide as much detail as possible so we can reproduce and fix it.

  - type: input
    id: yagsl-version
    attributes:
      label: "YAGSL Version"
      description: "Which version or commit of YAGSL are you using?"
      placeholder: "e.g. 2025.0.0"
    validations:
      required: true

  - type: input
    id: wpilib-version
    attributes:
      label: "WPILib Version"
      placeholder: "e.g. 2025.0.0"
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: "What motor controller(s) are you using?"
      multiple: true
      options:
        - TalonFX (Phoenix 6)
        - TalonSRX / VictorSPX (CTRE)
        - Spark MAX (REV)
        - Spark Flex (REV)
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: hardware-other
    attributes:
      label: "Other motor/hardware details (if any)"
      placeholder: "e.g. KrakenX60 on CAN ID 3"

  - type: textarea
    id: description
    attributes:
      label: "What went wrong?"
      description: "What did you expect to happen, and what actually happened?"
      placeholder: "Expected the PID controller to hold position, but..."

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Create a `PIDControlledMechanism`
        2. Set target to 50
        3. Observe motor behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs or Console Output"
      description: "Paste relevant stack traces, robot logs, or console output."
      render: shell

  - type: textarea
    id: code-snippet
    attributes:
      label: "Relevant Code (if any)"
      render: java
      description: "A minimal reproducible example would be very helpful."

  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I am using the latest YAGSL version"
          required: true
        - label: "I searched [existing issues](https://github.com/thenetworkgrinch/YAGSL/issues) for duplicates"
          required: true
